"""Canonical typed domain contracts generated by hand from contracts/schemas/.

The JSON Schemas are the product-contract source of truth.  These models must
reject fields/types that the corresponding Draft 2020-12 schema rejects; they
are not convenience view models and must not retain superseded field names.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import (
    AfterValidator, BaseModel, BeforeValidator, ConfigDict, Field, StrictBool,
    StrictFloat, StrictInt,
)


# ---------------------------------------------------------------------------
# Shared helpers / public enums
# ---------------------------------------------------------------------------
class CharacterKind(StrEnum):
    CANONICAL = "canonical"
    ORIGINAL = "original"
    NPC = "npc"


class InputMode(StrEnum):
    VOICE = "voice"
    TEXT = "text"
    SUGGESTION = "suggestion"


class AdherenceType(StrEnum):
    FULL = "full"
    PARTIAL = "partial"
    REINTERPRET = "reinterpret"
    REJECT = "reject"


class EndingType(StrEnum):
    """Known product endings; Episode schema intentionally permits future strings."""

    PARTIAL_TRUTH = "partial_truth"
    COMPLETE_TRUTH = "complete_truth"
    FATAL_DISTORTION = "fatal_distortion"
    CONTAINMENT_FAILURE = "containment_failure"


class SecretState(StrEnum):
    HIDDEN = "hidden"
    SUSPECTED = "suspected"
    PARTIAL = "partial"
    REVEALED = "revealed"


class KnowledgeStatus(StrEnum):
    CONFIRMED = "confirmed"
    PROBABLE = "probable"
    UNCERTAIN = "uncertain"
    CONTRADICTED = "contradicted"
    REVOKED = "revoked"


class KnowledgeSourceType(StrEnum):
    OBSERVATION = "observation"
    CONVERSATION = "conversation"
    DOCUMENT = "document"
    INVESTIGATION = "investigation"
    ABILITY = "ability"
    ORGANIZATION = "organization"
    CANON_EVENT = "canon_event"
    INFERENCE = "inference"
    MEMORY_RECALL = "memory_recall"


class ContractModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


def _unique_strings(value: list[str]) -> list[str]:
    if len(value) != len(set(value)):
        raise ValueError("items must be unique")
    return value


UniqueStrings = Annotated[list[str], AfterValidator(_unique_strings)]


def _json_integer(value: Any) -> Any:
    # JSON Schema defines numerically integral JSON numbers (for example 1.0)
    # as integers. Preserve that semantics without accepting bool/string coercion.
    if isinstance(value, float) and value.is_integer():
        return int(value)
    return value


JsonInteger = Annotated[StrictInt, BeforeValidator(_json_integer)]
BoundedUnit = Annotated[StrictFloat, Field(ge=0.0, le=1.0)]
NonNegativeInt = Annotated[JsonInteger, Field(ge=0)]
NonEmptyString = Annotated[str, Field(min_length=1)]
SchemaVersion = Literal["1.0"]


# ---------------------------------------------------------------------------
# Character — contracts/schemas/character.schema.json
# ---------------------------------------------------------------------------
class CharacterIdentity(ContractModel):
    display_name: NonEmptyString
    age: NonNegativeInt | None = None
    occupation: str | None = None
    pathway_id: str | None = None
    sequence: Annotated[JsonInteger, Field(ge=0, le=9)] | None = None


class CharacterSpeechStyle(ContractModel):
    tone: str | None = None
    verbosity: str | None = None
    formality: str | None = None
    humor: str | None = None
    metaphor: str | None = None


class CharacterCore(ContractModel):
    traits: dict[str, str]
    decision_style: UniqueStrings
    values: dict[str, str]
    hard_boundaries: UniqueStrings
    speech_style: CharacterSpeechStyle | None = None


class CharacterGoals(ContractModel):
    long: str | None = None
    medium: str | None = None
    immediate: str | None = None


class CharacterEmotion(ContractModel):
    primary: str | None = None
    intensity: BoundedUnit | None = None
    secondary: UniqueStrings = Field(default_factory=list)
    cause_ids: UniqueStrings = Field(default_factory=list)


class CharacterCondition(ContractModel):
    injury: str | None = None
    fatigue: BoundedUnit | None = None
    spirituality: StrictFloat | None = None
    corruption: BoundedUnit | None = None


class CharacterState(ContractModel):
    # Required + nullable in the schema: no default means omission is rejected.
    location_id: str | None
    goals: CharacterGoals
    emotion: CharacterEmotion | None = None
    condition: CharacterCondition | None = None


class Character(ContractModel):
    schema_version: SchemaVersion
    id: NonEmptyString
    kind: CharacterKind
    identity: CharacterIdentity
    canon_anchor: dict[str, Any] | None = None
    core: CharacterCore
    state: CharacterState
    revision: NonNegativeInt


# ---------------------------------------------------------------------------
# World Snapshot — contracts/schemas/world_snapshot.schema.json
# ---------------------------------------------------------------------------
class WorldLocation(ContractModel):
    id: NonEmptyString
    display_name: str | None = None
    city: str | None = None
    district: str | None = None
    open: StrictBool | None = None
    closes_at: str | None = None
    rooms: UniqueStrings = Field(default_factory=list)
    discovered_rooms: UniqueStrings = Field(default_factory=list)


class WorldSnapshot(ContractModel):
    schema_version: SchemaVersion
    world_id: str
    worldline_id: str
    world_time: str
    revision: NonNegativeInt
    location: WorldLocation
    weather: str | None = None


# ---------------------------------------------------------------------------
# Player Advice — contracts/schemas/player_advice.schema.json
# ---------------------------------------------------------------------------
class PlayerAdvice(ContractModel):
    schema_version: SchemaVersion
    id: str
    turn_id: str
    raw_input: NonEmptyString
    input_mode: InputMode
    primary_intent: str
    secondary_intents: UniqueStrings = Field(default_factory=list)
    proposed_actions: UniqueStrings
    risk_preference: str | None = None
    confidence: BoundedUnit


# ---------------------------------------------------------------------------
# Action Intent — contracts/schemas/action_intent.schema.json
# ---------------------------------------------------------------------------
class ActionStep(ContractModel):
    type: NonEmptyString
    purpose: str | None = None
    target_ids: UniqueStrings = Field(default_factory=list)
    parameters: dict[str, Any] = Field(default_factory=dict)


class ExpectedCost(ContractModel):
    resource: str
    amount: StrictFloat
    unit: str | None = None


class PerceivedRisk(ContractModel):
    risk: str
    level: BoundedUnit


class ActionIntent(ContractModel):
    schema_version: SchemaVersion
    id: str
    turn_id: str
    character_id: str
    intent: str
    adherence: AdherenceType
    actions: Annotated[list[ActionStep], Field(min_length=1)]
    reason_summary: str | None = None
    speech_intent: str | None = None
    evidence_ids: UniqueStrings
    expected_costs: list[ExpectedCost] = Field(default_factory=list)
    perceived_risks: list[PerceivedRisk] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Beat Plan — contracts/schemas/beat_plan.schema.json
# ---------------------------------------------------------------------------
class WorldEventOpportunity(ContractModel):
    event_type: NonEmptyString
    actor_ids: UniqueStrings = Field(default_factory=list)
    target_ids: UniqueStrings = Field(default_factory=list)
    purpose: str | None = None


class NPCIntent(ContractModel):
    character_id: NonEmptyString
    intent: str
    purpose: str | None = None


class BeatPlan(ContractModel):
    schema_version: SchemaVersion
    id: str
    story_session_id: str
    source_story_revision: NonNegativeInt
    beat_type: str
    dramatic_goal: str
    world_event_opportunities: list[WorldEventOpportunity] = Field(default_factory=list)
    reveal_ids: UniqueStrings = Field(default_factory=list)
    npc_intents: list[NPCIntent] = Field(default_factory=list)
    tension_delta: str | StrictFloat | None = None
    constraints: UniqueStrings = Field(default_factory=list)
    intervention_required: StrictBool


# ---------------------------------------------------------------------------
# Narrative Block — contracts/schemas/narrative_block.schema.json
# ---------------------------------------------------------------------------
class NarrativeSegment(ContractModel):
    type: Literal["narration", "character", "transition"]
    speaker_id: str | None = None
    text: str
    speech_intent: str | None = None


class AmbientCue(ContractModel):
    cue: NonEmptyString
    action: Literal["start", "continue", "duck", "stop"] | None = None
    level: BoundedUnit | None = None


class SFXCue(ContractModel):
    cue: NonEmptyString
    at_ms: NonNegativeInt | None = None


class NarrativeBlock(ContractModel):
    schema_version: SchemaVersion
    id: str
    story_session_id: str
    source_story_revision: NonNegativeInt
    scene_id: str | None = None
    segments: list[NarrativeSegment]
    ambient_cues: list[AmbientCue] = Field(default_factory=list)
    sfx_cues: list[SFXCue] = Field(default_factory=list)
    source_state_delta_id: str | None = None


# ---------------------------------------------------------------------------
# State Delta — contracts/schemas/state_delta.schema.json
# ---------------------------------------------------------------------------
class StoryPatch(ContractModel):
    path: NonEmptyString
    operation: Literal["set", "remove", "increment"]
    value: Any = None


class StoryDelta(ContractModel):
    scene_id: str | None = None
    world_time_delta_minutes: StrictFloat | None = None
    clue_ids_add: UniqueStrings = Field(default_factory=list)
    clue_ids_remove: UniqueStrings = Field(default_factory=list)
    secret_state_updates: dict[str, SecretState] = Field(default_factory=dict)
    local_state_patches: list[StoryPatch] = Field(default_factory=list)


class CharacterPatch(ContractModel):
    path: NonEmptyString
    operation: Literal["set", "remove", "increment", "add_to_set", "remove_from_set"]
    value: Any = None


class CharacterDelta(ContractModel):
    character_id: NonEmptyString
    patches: list[CharacterPatch]
    evidence_ids: UniqueStrings


class RelationshipDimensionDelta(ContractModel):
    trust: StrictFloat | None = None
    affection: StrictFloat | None = None
    respect: StrictFloat | None = None
    fear: StrictFloat | None = None
    dependency: StrictFloat | None = None
    hostility: StrictFloat | None = None


class RelationshipDelta(ContractModel):
    from_character_id: NonEmptyString
    to_character_id: NonEmptyString
    dimension_deltas: RelationshipDimensionDelta
    evidence_ids: UniqueStrings


class KnowledgeCandidate(ContractModel):
    character_id: NonEmptyString
    proposition_id: NonEmptyString
    certainty: BoundedUnit
    source_ref: NonEmptyString
    status: KnowledgeStatus


class EventVisibility(ContractModel):
    public: StrictBool
    known_by: UniqueStrings = Field(default_factory=list)
    possibly_known_by: UniqueStrings = Field(default_factory=list)


class WorldEventCandidate(ContractModel):
    event_type: NonEmptyString
    actors: UniqueStrings
    targets: UniqueStrings
    payload: dict[str, Any]
    visibility: EventVisibility


class StateDelta(ContractModel):
    schema_version: SchemaVersion
    id: str
    turn_id: str
    outcome: Literal[
        "clean_success", "success_with_cost", "partial_success",
        "complication", "failure", "catastrophic_failure",
    ]
    story_delta: StoryDelta
    character_deltas: list[CharacterDelta]
    relationship_deltas: list[RelationshipDelta] = Field(default_factory=list)
    knowledge_candidates: list[KnowledgeCandidate] = Field(default_factory=list)
    pressure_delta: dict[str, StrictFloat] = Field(default_factory=dict)
    world_event_candidates: list[WorldEventCandidate]
    evidence_ids: UniqueStrings


# ---------------------------------------------------------------------------
# Episode — contracts/schemas/episode.schema.json
# ---------------------------------------------------------------------------
class EpisodeEnding(ContractModel):
    type: str
    main_problem: str | None = None


class Episode(ContractModel):
    schema_version: SchemaVersion
    id: str
    world_id: str
    worldline_id: str
    story_seed_id: str | None = None
    protagonist_ids: UniqueStrings
    title: str
    # Required + nullable in the schema.
    start_world_time: str | None
    end_world_time: str | None = None
    ending: EpisodeEnding
    secret_states: dict[str, SecretState]
    narrative_block_ids: UniqueStrings = Field(default_factory=list)
    discovered_clue_ids: UniqueStrings = Field(default_factory=list)
    unresolved_threads: UniqueStrings
    worldline_divergence: StrictBool = False
    character_event_ids: UniqueStrings = Field(default_factory=list)
    relationship_event_ids: UniqueStrings = Field(default_factory=list)
    knowledge_change_ids: UniqueStrings = Field(default_factory=list)
    memory_ids: UniqueStrings = Field(default_factory=list)
    world_event_ids: UniqueStrings = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Character Knowledge — contracts/schemas/character_knowledge.schema.json
# ---------------------------------------------------------------------------
class KnowledgeSource(ContractModel):
    type: KnowledgeSourceType
    ref: str
    reliability: BoundedUnit | None = None


class CharacterKnowledge(ContractModel):
    schema_version: SchemaVersion
    id: str
    character_id: str
    worldline_id: str
    proposition_id: str
    certainty: BoundedUnit
    source: KnowledgeSource
    acquired_world_time: str | None = None
    status: KnowledgeStatus
    revision: NonNegativeInt
