"""Audio Infrastructure Package (OpenAI SDK & SpeechRail Integration)."""

from .capabilities import (
    AudioCapabilityObservation,
    ProbeHttpResponse,
    RealtimeResponsibilityObservation,
    VoiceCapabilityObservation,
    probe_audio_capabilities,
)
from .config import AudioProviderConfig
from .media_protocol import (
    MEDIA_MAX_HEADER_BYTES,
    MEDIA_MAX_PAYLOAD_BYTES,
    MediaCancelHeader,
    MediaChunkHeader,
    MediaCreditHeader,
    MediaCreditWindow,
    MediaEndHeader,
    MediaErrorHeader,
    MediaFormat,
    MediaGrant,
    MediaGrantStore,
    MediaOpenHeader,
    MediaProtocolError,
    MediaReceiveState,
    encode_media_frame,
    parse_media_header,
    read_media_frame,
    write_media_frame,
)
from .mock_adapter import MockAudioAdapter
from .openai_adapter import OpenAIAudioAdapter, create_audio_adapter
from .websocket_transport import JSONWebSocketTransportError, StdlibJSONWebSocketTransport
from .render_receipts import (
    HttpRenderReceiptReader,
    RenderReceiptError,
    RenderReceiptReader,
    create_render_receipt_reader,
)
from .realtime_tts import (
    REALTIME_TTS_SAMPLE_RATE,
    RECEIPT_INTEGRITY_BOUNDARY,
    WIRE_REVISION,
    RealtimeTTSChunk,
    RealtimeTTSPhase,
    RealtimeTTSRequest,
    RealtimeTTSStatus,
    RealtimeTTSTerminal,
    RealtimeTTSTransport,
    SpeechRailRealtimeTTSAdapter,
    SpeechRailRealtimeTTSError,
    create_realtime_tts_adapter,
    split_text_segments,
)
from .media_bridge import (
    EngineRealtimeTTSMediaStream,
    MediaPeerStop,
    RealtimeTTSMediaBridgeError,
    render_realtime_tts_to_media,
)

from .voice_control import (
    PendingVoiceRender,
    PendingVoiceRenderRegistry,
    VoiceRenderAccepted,
    EVIDENCE_PIN_FIELDS,
    VoiceRenderControlError,
    VoiceRenderControlRequest,
)

__all__ = [
    "AudioCapabilityObservation",
    "AudioProviderConfig",
    "MEDIA_MAX_HEADER_BYTES",
    "MEDIA_MAX_PAYLOAD_BYTES",
    "MediaCancelHeader",
    "MediaChunkHeader",
    "MediaCreditHeader",
    "MediaCreditWindow",
    "MediaEndHeader",
    "MediaErrorHeader",
    "MediaFormat",
    "MediaGrant",
    "MediaGrantStore",
    "MediaOpenHeader",
    "MediaProtocolError",
    "MediaReceiveState",
    "MockAudioAdapter",
    "encode_media_frame",
    "parse_media_header",
    "read_media_frame",
    "write_media_frame",
    "OpenAIAudioAdapter",
    "PendingVoiceRender",
    "PendingVoiceRenderRegistry",
    "VoiceRenderAccepted",
    "EVIDENCE_PIN_FIELDS",
    "VoiceRenderControlError",
    "VoiceRenderControlRequest",
    "ProbeHttpResponse",
    "RealtimeResponsibilityObservation",
    "EngineRealtimeTTSMediaStream",
    "MediaPeerStop",
    "RealtimeTTSMediaBridgeError",
    "REALTIME_TTS_SAMPLE_RATE",
    "RECEIPT_INTEGRITY_BOUNDARY",
    "WIRE_REVISION",
    "HttpRenderReceiptReader",
    "RenderReceiptError",
    "RenderReceiptReader",
    "RealtimeTTSChunk",
    "RealtimeTTSPhase",
    "RealtimeTTSRequest",
    "RealtimeTTSStatus",
    "RealtimeTTSTerminal",
    "RealtimeTTSTransport",
    "VoiceCapabilityObservation",
    "SpeechRailRealtimeTTSAdapter",
    "SpeechRailRealtimeTTSError",
    "JSONWebSocketTransportError",
    "StdlibJSONWebSocketTransport",
    "create_audio_adapter",
    "create_realtime_tts_adapter",
    "create_render_receipt_reader",
    "split_text_segments",
    "render_realtime_tts_to_media",
    "probe_audio_capabilities",
]

from .delivery_control import (
    DeliveryCursorControlRuntime,
    DeliveryCursorGetRequest,
    DeliveryCursorUpdateRequest,
)
